#pragma once

#define PROJECT_NAME "${PROJECT_NAME}"
#define CMAKE_PROJECT_VERSION "${CMAKE_PROJECT_VERSION}"
#define CMAKE_PROJECT_VERSION_MAJOR "${CMAKE_PROJECT_VERSION_MAJOR}"
#define CMAKE_PROJECT_VERSION_MINOR "${CMAKE_PROJECT_VERSION_MINOR}"
#define CMAKE_PROJECT_VERSION_PATCH "${CMAKE_PROJECT_VERSION_PATCH}"
#define CMAKE_PROJECT_VERSION_TWEAK "${CMAKE_PROJECT_VERSION_TWEAK}"