name: CMake on multiple platforms

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -Bbuild

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      run: ./build/AA_test

    - uses: actions/setup-python@v5
    - run: python -m pip install gcovr
    - name: gcovr
      run: gcovr --filter "source/" --exclude "source/main.cpp"
