name: CMake on multiple platforms

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -Bbuild

      - name: Build
        run: cmake --build build --parallel --target AA_test

      - name: Test
        run: ./build/AA_test

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: python -m pip install gcovr

      - run: |
          gcovr --filter source  --json | jq ".files.[].functions.[].blocks_percent" | awk '{ total += $1; count++ } END { print "", total/count }'
