name: CMake on multiple platforms

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -Bbuild

      - name: Build
        run: cmake --build build --parallel --target AA_test

      - name: Test
        run: ./build/AA_test

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: sudo apt install lcov -y

      - run: |
          lcov --directory ./build/CMakeFiles/AA_lib.dir -c -o coverage.xml
          lcov --remove coverage.xml -o coverage.xml "source/main.cpp" "tests"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      # - run: |
      #     gcovr --filter source  --json | jq ".files.[].functions.[].blocks_percent" | awk '{ total += $1; count++ } END { print "", total/count }'
